name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.0
  equatable: ^2.0.5

  # Networking & API
  dio: ^5.3.2
  http: ^0.13.6

  # Persistence
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^9.0.0

  # Utilities
  intl: ^0.18.0
  uuid: ^3.0.7
  crypto: ^3.0.3
  email_validator: ^2.1.17

  # UI/UX Features
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  cached_network_image: ^3.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
